import React, { useEffect, useState } from 'react';
import { Archive, ImageOff, Pencil, RotateCcw, Save, Trash2, X } from 'lucide-react';
import type { components } from '../../api/generated';
import { type TestimonyAdminListParams, useCreateAnnouncement, useCreateTestimony, useDeleteAnnouncement, useDeleteTestimony, useManagedAnnouncements, useManagedTestimonies, useRestoreAnnouncement, useUpdateAnnouncement, useUpdateTestimony } from '../../api/hooks';
import { AdminListControls, AdminListState, AdminPagination, FilterField, useAdminListState } from './AdminList';
import { ConfirmDialog } from './ConfirmDialog';

type S = components['schemas'];
type Announcement = S['ManagedAnnouncement']; type AnnouncementInput = S['CreateAnnouncementRequest'];
type Testimony = S['ManagedTestimony'];
type TestimonyInput = Omit<S['CreateTestimonyRequest'], 'coverImage'> & { coverImage?: File };
type TestimonyUpdate = Omit<S['UpdateTestimonyRequest'], 'coverImage'> & { coverImage?: File };
type Track = { id: string; name: string };

const localDateTime = (value?: string | null) => value ? value.slice(0, 16) : '';
const apiDateTime = (value: string) => value ? new Date(value).toISOString() : null;

function MultiCheck({ label, values, options, onChange }: { label: string; values: string[]; options: { value: string; label: string }[]; onChange: (values: string[]) => void }) {
  return <fieldset className="md:col-span-2"><legend className="text-xs font-bold">{label}</legend><div className="mt-2 flex flex-wrap gap-3">{options.map(option => <label key={option.value} className="flex items-center gap-1 text-xs"><input type="checkbox" checked={values.includes(option.value)} onChange={event => onChange(event.target.checked ? [...values, option.value] : values.filter(value => value !== option.value))} />{option.label}</label>)}</div></fieldset>;
}

function AnnouncementForm({ initial, tracks, busy, onCancel, onSubmit }: { initial: AnnouncementInput; tracks: Track[]; busy: boolean; onCancel: () => void; onSubmit: (input: AnnouncementInput) => Promise<void> }) {
  const [form, setForm] = useState(initial); const [error, setError] = useState('');
  useEffect(() => setForm(initial), [initial]);
  const set = <K extends keyof AnnouncementInput>(key: K, value: AnnouncementInput[K]) => setForm(current => ({ ...current, [key]: value }));
  return <form className="grid gap-3 rounded-2xl border bg-editorial-card p-5 md:grid-cols-2" onSubmit={event => { event.preventDefault(); if (!form.title.trim() || !form.description.trim()) return setError('Title and description are required.'); if (form.audienceType === 'roles' && !form.targetRoles?.length) return setError('Choose at least one target role.'); if (form.audienceType === 'tracks' && !form.targetTrackIds?.length) return setError('Choose at least one target track.'); if (form.startsAt && form.endsAt && new Date(form.endsAt) <= new Date(form.startsAt)) return setError('End time must be after start time.'); setError(''); const input = { ...form, startsAt: apiDateTime(form.startsAt || ''), endsAt: apiDateTime(form.endsAt || '') }; if (input.audienceType !== 'roles') delete input.targetRoles; if (input.audienceType !== 'tracks') delete input.targetTrackIds; onSubmit(input); }}>
    <label className="text-xs font-bold">Title<input required maxLength={100} value={form.title} onChange={e => set('title', e.target.value)} className="mt-1 w-full rounded-xl border bg-transparent p-2 font-normal" /></label><label className="text-xs font-bold">Status<select value={form.status || 'draft'} onChange={e => set('status', e.target.value as AnnouncementInput['status'])} className="mt-1 w-full rounded-xl border bg-editorial-card p-2 font-normal"><option value="draft">Draft</option><option value="published">Published</option></select></label>
    <label className="text-xs font-bold md:col-span-2">Description<textarea required maxLength={500} rows={4} value={form.description} onChange={e => set('description', e.target.value)} className="mt-1 w-full rounded-xl border bg-transparent p-2 font-normal" /></label>
    <label className="text-xs font-bold">Type<select value={form.type || 'info'} onChange={e => set('type', e.target.value as AnnouncementInput['type'])} className="mt-1 w-full rounded-xl border bg-editorial-card p-2 font-normal"><option value="info">Info</option><option value="warning">Warning</option><option value="urgent">Urgent</option></select></label><label className="text-xs font-bold">Priority<select value={form.priority || 'normal'} onChange={e => set('priority', e.target.value as AnnouncementInput['priority'])} className="mt-1 w-full rounded-xl border bg-editorial-card p-2 font-normal"><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option></select></label>
    <label className="text-xs font-bold">Starts at<input type="datetime-local" value={localDateTime(form.startsAt)} onChange={e => set('startsAt', e.target.value || null)} className="mt-1 w-full rounded-xl border bg-transparent p-2 font-normal" /></label><label className="text-xs font-bold">Ends at<input type="datetime-local" value={localDateTime(form.endsAt)} onChange={e => set('endsAt', e.target.value || null)} className="mt-1 w-full rounded-xl border bg-transparent p-2 font-normal" /></label>
    <label className="text-xs font-bold">Audience<select value={form.audienceType} onChange={e => set('audienceType', e.target.value as AnnouncementInput['audienceType'])} className="mt-1 w-full rounded-xl border bg-editorial-card p-2 font-normal"><option value="global">Global</option><option value="roles">Roles</option><option value="tracks">Tracks</option></select></label>
    {form.audienceType === 'roles' && <MultiCheck label="Target roles" values={form.targetRoles || []} options={['admin', 'family', 'friend'].map(value => ({ value, label: value }))} onChange={values => set('targetRoles', values as NonNullable<AnnouncementInput['targetRoles']>)} />}
    {form.audienceType === 'tracks' && <MultiCheck label="Target tracks" values={form.targetTrackIds || []} options={tracks.map(track => ({ value: track.id, label: track.name }))} onChange={values => set('targetTrackIds', values)} />}
    {error && <p role="alert" className="text-xs text-rose-600 md:col-span-2">{error}</p>}<div className="flex justify-end gap-2 md:col-span-2"><button type="button" onClick={onCancel} className="rounded-full border px-4 py-2 text-xs"><X className="mr-1 inline h-3 w-3" />Cancel</button><button disabled={busy} className="rounded-full bg-editorial-charcoal px-4 py-2 text-xs font-bold text-editorial-cream"><Save className="mr-1 inline h-3 w-3" />Save</button></div>
  </form>;
}

const newAnnouncement: AnnouncementInput = { title: '', description: '', type: 'info', priority: 'normal', status: 'draft', audienceType: 'global' };

export function AdminAnnouncements({ tracks }: { tracks: Track[] }) {
  const { query, update } = useAdminListState('announcements', { page: 1, limit: 20, search: '', status: '', visibilityState: '', audienceType: '', type: '', priority: '' });
  const params = Object.fromEntries(Object.entries(query).map(([key, value]) => [key, value === '' ? undefined : value]));
  const list = useManagedAnnouncements(params); const create = useCreateAnnouncement(); const save = useUpdateAnnouncement(); const restore = useRestoreAnnouncement(); const remove = useDeleteAnnouncement();
  const [editing, setEditing] = useState<Announcement | 'new' | null>(null); const [confirm, setConfirm] = useState<{ item: Announcement; action: 'archive' | 'restore' | 'delete' } | null>(null); const [error, setError] = useState('');
  const run = async (operation: () => Promise<unknown>) => { setError(''); try { await operation(); setEditing(null); setConfirm(null); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Announcement action failed.'); } };
  const initial = editing === 'new' ? newAnnouncement : editing ? { title: editing.title, description: editing.description, type: editing.type, priority: editing.priority, status: editing.status === 'archived' ? 'published' as const : editing.status, audienceType: editing.audienceType, targetRoles: editing.targetRoles, targetTrackIds: editing.targetTrackIds, startsAt: editing.startsAt, endsAt: editing.endsAt } : null;
  return <div className="space-y-4"><div className="flex items-center justify-between"><div><h2 className="text-2xl font-serif">Announcements</h2><p className="text-xs text-editorial-charcoal/50">Draft, schedule, target, publish, and archive announcements.</p></div><button onClick={() => setEditing('new')} className="rounded-full bg-editorial-charcoal px-4 py-2 text-xs font-bold text-editorial-cream">Create announcement</button></div>
    {initial && <AnnouncementForm initial={initial} tracks={tracks} busy={create.isPending || save.isPending} onCancel={() => setEditing(null)} onSubmit={input => run(() => editing === 'new' ? create.mutateAsync(input) : save.mutateAsync({ id: (editing as Announcement).id, input }))} />}
    <AdminListControls query={query} onChange={update}>{([['Status', 'status', ['', 'draft', 'published', 'archived']], ['Visibility', 'visibilityState', ['', 'draft', 'scheduled', 'active', 'expired', 'archived']], ['Audience', 'audienceType', ['', 'global', 'roles', 'tracks']], ['Type', 'type', ['', 'info', 'warning', 'urgent']], ['Priority', 'priority', ['', 'low', 'normal', 'high']]] as const).map(([label, key, values]) => <FilterField key={key} label={label}><select value={query[key]} onChange={e => update({ [key]: e.target.value })}>{values.map(value => <option key={value} value={value}>{value || 'All'}</option>)}</select></FilterField>)}</AdminListControls>
    {error && <p role="alert" className="rounded-xl bg-rose-500/10 p-3 text-xs text-rose-600">{error}</p>}<AdminListState loading={list.isLoading} error={list.error} empty={!list.data?.announcements.length}><div className="space-y-3">{list.data?.announcements.map(item => <article key={item.id} className="rounded-2xl border bg-editorial-card p-4"><div className="flex flex-wrap gap-3"><div className="min-w-0 flex-1"><h3 className="text-sm font-bold">{item.title}</h3><p className="mt-1 line-clamp-2 text-xs text-editorial-charcoal/60">{item.description}</p><p className="mt-2 text-[10px] text-editorial-charcoal/45">{item.status} · {item.visibilityState} · {item.audienceType} · {item.type}/{item.priority}</p><p className="mt-1 text-[10px] text-editorial-charcoal/45">Schedule: {item.startsAt ? new Date(item.startsAt).toLocaleString() : 'immediate'} → {item.endsAt ? new Date(item.endsAt).toLocaleString() : 'open-ended'} · Updated {new Date(item.updatedAt).toLocaleString()}</p></div>{item.status !== 'archived' && <button onClick={() => setEditing(item)} title="Edit"><Pencil className="h-4 w-4" /></button>}{item.status === 'archived' ? <button onClick={() => setConfirm({ item, action: 'restore' })} title="Restore"><RotateCcw className="h-4 w-4" /></button> : item.status === 'published' ? <button onClick={() => setConfirm({ item, action: 'archive' })} title="Archive"><Archive className="h-4 w-4" /></button> : null}{item.status === 'draft' && <button onClick={() => setConfirm({ item, action: 'delete' })} title="Delete"><Trash2 className="h-4 w-4 text-rose-600" /></button>}</div></article>)}</div></AdminListState>
    {list.data && <AdminPagination page={list.data.page} limit={list.data.limit} total={list.data.total} totalPages={list.data.totalPages} onChange={update} />}<ConfirmDialog open={!!confirm} title={`${confirm?.action === 'restore' ? 'Restore' : confirm?.action === 'delete' ? 'Delete' : 'Archive'} announcement?`} description={confirm?.action === 'delete' ? 'Only drafts can be permanently deleted. This cannot be undone.' : confirm?.action === 'restore' ? 'The announcement will return to published status using its retained schedule and audience.' : 'The announcement will leave active feeds and remain available in the archived view.'} confirmLabel={confirm?.action} destructive={confirm?.action !== 'restore'} busy={save.isPending || restore.isPending || remove.isPending} onCancel={() => setConfirm(null)} onConfirm={() => confirm && run(() => confirm.action === 'delete' ? remove.mutateAsync(confirm.item.id) : confirm.action === 'restore' ? restore.mutateAsync(confirm.item.id) : save.mutateAsync({ id: confirm.item.id, input: { status: 'archived' } }))} />
  </div>;
}

function TestimonyForm({ initial, tracks, busy, onCancel, onSubmit }: { initial: TestimonyInput; tracks: Track[]; busy: boolean; onCancel: () => void; onSubmit: (input: TestimonyInput | TestimonyUpdate) => Promise<void> }) {
  const [form, setForm] = useState<TestimonyInput>(initial); const [error, setError] = useState(''); useEffect(() => setForm(initial), [initial]);
  const set = <K extends keyof TestimonyInput>(key: K, value: TestimonyInput[K]) => setForm(current => ({ ...current, [key]: value }));
  return <form className="grid gap-3 rounded-2xl border bg-editorial-card p-5 md:grid-cols-2" onSubmit={event => { event.preventDefault(); if (!form.authorName.trim() || !form.quote.trim()) return setError('Author and testimony are required.'); if (form.startsAt && form.endsAt && new Date(form.endsAt) <= new Date(form.startsAt)) return setError('End time must be after start time.'); setError(''); onSubmit({ ...form, startsAt: apiDateTime(form.startsAt || ''), endsAt: apiDateTime(form.endsAt || ''), testimonyDate: form.testimonyDate ? new Date(form.testimonyDate).toISOString() : null, ministryTrackId: form.ministryTrackId || null }); }}>
    <label className="text-xs font-bold">Author name<input required maxLength={100} value={form.authorName} onChange={e => set('authorName', e.target.value)} className="mt-1 w-full rounded-xl border bg-transparent p-2 font-normal" /></label><label className="text-xs font-bold">Author location<input maxLength={150} value={form.authorLocation || ''} onChange={e => set('authorLocation', e.target.value || null)} className="mt-1 w-full rounded-xl border bg-transparent p-2 font-normal" /></label>
    <label className="text-xs font-bold md:col-span-2">Testimony<textarea required maxLength={5000} rows={5} value={form.quote} onChange={e => set('quote', e.target.value)} className="mt-1 w-full rounded-xl border bg-transparent p-2 font-normal" /></label>
    <label className="text-xs font-bold">Track<select value={form.ministryTrackId || ''} onChange={e => set('ministryTrackId', e.target.value || null)} className="mt-1 w-full rounded-xl border bg-editorial-card p-2 font-normal"><option value="">Global</option>{tracks.map(track => <option key={track.id} value={track.id}>{track.name}</option>)}</select></label><label className="text-xs font-bold">Status<select value={form.status || 'draft'} onChange={e => set('status', e.target.value as TestimonyInput['status'])} className="mt-1 w-full rounded-xl border bg-editorial-card p-2 font-normal"><option value="draft">Draft</option><option value="published">Published</option></select></label>
    <label className="text-xs font-bold">Testimony date<input type="date" value={form.testimonyDate?.slice(0, 10) || ''} onChange={e => set('testimonyDate', e.target.value || null)} className="mt-1 w-full rounded-xl border bg-transparent p-2 font-normal" /></label><label className="text-xs font-bold">Cover image<input type="file" accept="image/*" onChange={e => set('coverImage', e.target.files?.[0])} className="mt-2 block w-full text-xs font-normal" /></label>
    <label className="text-xs font-bold">Starts at<input type="datetime-local" value={localDateTime(form.startsAt)} onChange={e => set('startsAt', e.target.value || null)} className="mt-1 w-full rounded-xl border bg-transparent p-2 font-normal" /></label><label className="text-xs font-bold">Ends at<input type="datetime-local" value={localDateTime(form.endsAt)} onChange={e => set('endsAt', e.target.value || null)} className="mt-1 w-full rounded-xl border bg-transparent p-2 font-normal" /></label>
    {error && <p role="alert" className="text-xs text-rose-600 md:col-span-2">{error}</p>}<div className="flex justify-end gap-2 md:col-span-2"><button type="button" onClick={onCancel} className="rounded-full border px-4 py-2 text-xs">Cancel</button><button disabled={busy} className="rounded-full bg-editorial-charcoal px-4 py-2 text-xs font-bold text-editorial-cream"><Save className="mr-1 inline h-3 w-3" />Save</button></div>
  </form>;
}

export function AdminTestimonies({ tracks }: { tracks: Track[] }) {
  const { query, update } = useAdminListState('testimonies', { page: 1, limit: 20, search: '', status: '', visibilityState: '' }); const params = { ...query, status: query.status || undefined, visibilityState: query.visibilityState || undefined };
  const list = useManagedTestimonies(params as TestimonyAdminListParams); const create = useCreateTestimony(); const save = useUpdateTestimony(); const remove = useDeleteTestimony(); const [editing, setEditing] = useState<Testimony | 'new' | null>(null); const [confirm, setConfirm] = useState<{ item: Testimony; action: 'archive' | 'restore' | 'removeImage' | 'delete' } | null>(null); const [error, setError] = useState('');
  const run = async (operation: () => Promise<unknown>) => { setError(''); try { await operation(); setEditing(null); setConfirm(null); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Testimony action failed.'); } };
  const initial: TestimonyInput | null = editing === 'new' ? { quote: '', authorName: '', status: 'draft', ministryTrackId: null } : editing ? { quote: editing.quote, authorName: editing.authorName, authorLocation: editing.authorLocation, testimonyDate: editing.testimonyDate, ministryTrackId: editing.track?.id || null, status: editing.status === 'archived' ? 'published' : editing.status, startsAt: editing.startsAt, endsAt: editing.endsAt } : null;
  return <div className="space-y-4"><div className="flex items-center justify-between"><div><h2 className="text-2xl font-serif">Testimonies</h2><p className="text-xs text-editorial-charcoal/50">Manage testimony copy, imagery, scheduling, and publication.</p></div><button onClick={() => setEditing('new')} className="rounded-full bg-editorial-charcoal px-4 py-2 text-xs font-bold text-editorial-cream">Create testimony</button></div>{initial && <TestimonyForm initial={initial} tracks={tracks} busy={create.isPending || save.isPending} onCancel={() => setEditing(null)} onSubmit={input => run(() => editing === 'new' ? create.mutateAsync(input as TestimonyInput) : save.mutateAsync({ id: (editing as Testimony).id, input: input as TestimonyUpdate }))} />}
    <AdminListControls query={query} onChange={update}><FilterField label="Status"><select value={query.status} onChange={e => update({ status: e.target.value })}><option value="">All</option><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></FilterField><FilterField label="Visibility"><select value={query.visibilityState} onChange={e => update({ visibilityState: e.target.value })}><option value="">All</option><option value="draft">Draft</option><option value="scheduled">Scheduled</option><option value="active">Active</option><option value="expired">Expired</option><option value="archived">Archived</option></select></FilterField></AdminListControls>
    {error && <p role="alert" className="rounded-xl bg-rose-500/10 p-3 text-xs text-rose-600">{error}</p>}<AdminListState loading={list.isLoading} error={list.error} empty={!list.data?.testimonies.length}><div className="space-y-3">{list.data?.testimonies.map(item => <article key={item.id} className="rounded-2xl border bg-editorial-card p-4"><div className="flex flex-wrap gap-3">{item.coverImageUrl && <img src={item.coverImageUrl} alt="" className="h-16 w-20 rounded-xl object-cover" />}<div className="min-w-0 flex-1"><h3 className="text-sm font-bold">{item.authorName}{item.authorLocation ? ` · ${item.authorLocation}` : ''}</h3><p className="mt-1 line-clamp-2 text-xs text-editorial-charcoal/60">{item.quote}</p><p className="mt-2 text-[10px] text-editorial-charcoal/45">{item.status} · {item.visibilityState} · {item.track?.name || 'Global'} · {item.testimonyDate ? new Date(item.testimonyDate).toLocaleDateString() : 'No testimony date'}</p></div>{item.status !== 'archived' && <button onClick={() => setEditing(item)} title="Edit"><Pencil className="h-4 w-4" /></button>}{item.coverImageUrl && item.status !== 'archived' && <button onClick={() => setConfirm({ item, action: 'removeImage' })} title="Remove cover image"><ImageOff className="h-4 w-4" /></button>}{item.status === 'archived' ? <button onClick={() => setConfirm({ item, action: 'restore' })} title="Restore"><RotateCcw className="h-4 w-4" /></button> : item.status === 'published' ? <button onClick={() => setConfirm({ item, action: 'archive' })} title="Archive"><Archive className="h-4 w-4" /></button> : null}{item.status === 'draft' && <button onClick={() => setConfirm({ item, action: 'delete' })} title="Delete"><Trash2 className="h-4 w-4 text-rose-600" /></button>}</div></article>)}</div></AdminListState>{list.data && <AdminPagination page={list.data.page} limit={list.data.limit} total={list.data.total} totalPages={list.data.totalPages} onChange={update} />}
    <ConfirmDialog open={!!confirm} title={confirm?.action === 'removeImage' ? 'Remove cover image?' : `${confirm?.action === 'restore' ? 'Restore' : confirm?.action === 'delete' ? 'Delete' : 'Archive'} testimony?`} description={confirm?.action === 'removeImage' ? 'The current file will be removed from this testimony.' : confirm?.action === 'delete' ? 'Only drafts can be permanently deleted. This cannot be undone.' : confirm?.action === 'restore' ? 'The testimony will return to published status.' : 'The testimony will leave active feeds and remain in the archived view.'} confirmLabel={confirm?.action} destructive={confirm?.action !== 'restore'} busy={save.isPending || remove.isPending} onCancel={() => setConfirm(null)} onConfirm={() => confirm && run(() => confirm.action === 'delete' ? remove.mutateAsync(confirm.item.id) : save.mutateAsync({ id: confirm.item.id, input: confirm.action === 'removeImage' ? { coverImageUrl: null } : { status: confirm.action === 'restore' ? 'published' : 'archived' } }))} />
  </div>;
}
