import React, { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Mail, Save, ShieldOff, Trash2, UserCheck } from 'lucide-react';
import type { components } from '../../api/generated';
import { type UserListParams, useDeleteUser, useResendUserInvitation, useUpdateUser, useUser, useUserBadges, useUserPayments, useUserPrayerActivity, useUsers } from '../../api/hooks';
import { AdminListControls, AdminListState, AdminPagination, FilterField, useAdminListState } from './AdminList';
import { ConfirmDialog } from './ConfirmDialog';

type User = components['schemas']['User'];
type UserUpdate = Omit<components['schemas']['UpdateUserRequest'], 'profilePictureUrl'> & { profilePictureUrl?: File };

function date(value?: string | null) { return value ? new Date(value).toLocaleString() : 'Not recorded'; }

export function AdminUsers({ currentUserId, selectedUserId, onOpenUser, onCloseUser }: { currentUserId: string; selectedUserId?: string; onOpenUser: (id: string) => void; onCloseUser: () => void }) {
  if (selectedUserId) return <AdminUserDetail id={selectedUserId} currentUserId={currentUserId} onBack={onCloseUser} />;
  return <AdminUserList onOpenUser={onOpenUser} />;
}

function AdminUserList({ onOpenUser }: { onOpenUser: (id: string) => void }) {
  const { query, update } = useAdminListState('users', { page: 1, limit: 20, search: '', role: '', isActive: '', sortBy: 'createdAt', sortOrder: 'DESC' });
  const params = { ...query, role: query.role || undefined, isActive: query.isActive === '' ? undefined : query.isActive === 'true' };
  const users = useUsers(params as UserListParams);
  return <div className="space-y-4">
    <div><h2 className="text-2xl font-serif">Users</h2><p className="text-xs text-editorial-charcoal/50">Select a user to edit their account and review available activity.</p></div>
    <AdminListControls query={query} onChange={update} searchPlaceholder="Search name or email"><FilterField label="Role"><select value={query.role} onChange={e => update({ role: e.target.value })}><option value="">All roles</option><option value="admin">Admin</option><option value="family">Family</option><option value="friend">Friend</option></select></FilterField><FilterField label="Active state"><select value={query.isActive} onChange={e => update({ isActive: e.target.value })}><option value="">All</option><option value="true">Active</option><option value="false">Inactive</option></select></FilterField><FilterField label="Sort by"><select value={query.sortBy} onChange={e => update({ sortBy: e.target.value })}>{['createdAt', 'firstName', 'lastName', 'email', 'role', 'isActive', 'lastLoginAt'].map(value => <option key={value}>{value}</option>)}</select></FilterField><FilterField label="Order"><select value={query.sortOrder} onChange={e => update({ sortOrder: e.target.value })}><option>DESC</option><option>ASC</option></select></FilterField></AdminListControls>
    <AdminListState loading={users.isLoading} error={users.error} empty={!users.data?.users.length}><div className="divide-y divide-editorial-charcoal/10 overflow-hidden rounded-2xl border border-editorial-charcoal/10 bg-editorial-card">{users.data?.users.map(user => <button key={user.id} onClick={() => onOpenUser(user.id)} className="flex w-full items-center gap-4 p-4 text-left transition hover:bg-editorial-charcoal/5"><img src={user.profilePictureUrl || `https://ui-avatars.com/api/?name=${encodeURIComponent(user.firstName)}&background=eeeae0&color=292827`} alt="" className="h-10 w-10 rounded-full object-cover" /><span className="min-w-0 flex-1"><span className="block truncate text-sm font-bold">{user.firstName} {user.lastName}</span><span className="block truncate text-[10px] text-editorial-charcoal/50">{user.email} · {user.role}</span></span><span className={`rounded-full px-2 py-1 text-[9px] font-bold uppercase ${user.isActive ? 'bg-emerald-500/10 text-emerald-700' : 'bg-rose-500/10 text-rose-700'}`}>{user.isActive ? 'Active' : 'Inactive'}</span></button>)}</div></AdminListState>
    {users.data && <AdminPagination page={users.data.page} limit={users.data.limit} total={users.data.total} totalPages={users.data.totalPages} onChange={update} />}
  </div>;
}

function AdminUserDetail({ id, currentUserId, onBack }: { id: string; currentUserId: string; onBack: () => void }) {
  const detail = useUser(id); const badges = useUserBadges(id); const payments = useUserPayments(id, { page: 1, limit: 20 }); const prayer = useUserPrayerActivity(id, { page: 1, limit: 20 }); const update = useUpdateUser(); const remove = useDeleteUser(); const resend = useResendUserInvitation();
  const user = detail.data?.user;
  const [form, setForm] = useState<UserUpdate>({}); const [error, setError] = useState(''); const [confirm, setConfirm] = useState<'deactivate' | 'reactivate' | 'delete' | null>(null);
  useEffect(() => { if (user) setForm({ firstName: user.firstName, lastName: user.lastName, email: user.email, role: user.role, isActive: user.isActive }); }, [user]);
  const progress = useMemo(() => { const records = badges.data || []; return { earned: records.filter(item => item.earned).length, total: records.length }; }, [badges.data]);
  const run = async (operation: () => Promise<unknown>, after?: () => void) => { setError(''); try { await operation(); setConfirm(null); after?.(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'User action failed.'); } };
  if (detail.isLoading) return <AdminListState loading error={null} empty={false}><span /></AdminListState>;
  if (detail.error || !user) return <><button onClick={onBack} className="mb-4 text-xs"><ArrowLeft className="mr-1 inline h-4 w-4" />Back to users</button><AdminListState loading={false} error={detail.error || new Error('User not found.')} empty={false}><span /></AdminListState></>;
  const field = <K extends keyof UserUpdate>(key: K, value: UserUpdate[K]) => setForm(current => ({ ...current, [key]: value }));
  const saveInput = () => { const input = { ...form }; if (!input.password) delete input.password; return input; };
  const isSelf = id === currentUserId;
  return <div className="space-y-5">
    <button onClick={onBack} className="text-xs"><ArrowLeft className="mr-1 inline h-4 w-4" />Back to users</button>
    <div className="flex flex-wrap items-start gap-4"><img src={user.profilePictureUrl || `https://ui-avatars.com/api/?name=${encodeURIComponent(user.firstName)}&background=eeeae0&color=292827`} alt="" className="h-20 w-20 rounded-2xl object-cover" /><div className="min-w-0 flex-1"><p className="text-[9px] font-bold uppercase tracking-widest text-editorial-charcoal/45">User detail</p><h2 className="font-serif text-3xl">{user.firstName} {user.lastName}</h2><p className="text-xs text-editorial-charcoal/50">{user.email}</p></div></div>
    {error && <p role="alert" className="rounded-xl bg-rose-500/10 p-3 text-xs text-rose-600">{error}</p>}
    <form onSubmit={event => { event.preventDefault(); if (!String(form.firstName || '').trim() || !String(form.email || '').trim()) { setError('First name and email are required.'); return; } run(() => update.mutateAsync({ id, input: saveInput() })); }} className="grid gap-3 rounded-2xl border border-editorial-charcoal/10 bg-editorial-card p-5 md:grid-cols-2">
      <label className="text-xs font-bold">First name<input required maxLength={50} value={form.firstName || ''} onChange={e => field('firstName', e.target.value)} className="mt-1 w-full rounded-xl border bg-transparent p-2 font-normal" /></label>
      <label className="text-xs font-bold">Last name<input maxLength={50} value={form.lastName || ''} onChange={e => field('lastName', e.target.value || null)} className="mt-1 w-full rounded-xl border bg-transparent p-2 font-normal" /></label>
      <label className="text-xs font-bold">Email<input required type="email" value={form.email || ''} onChange={e => field('email', e.target.value)} className="mt-1 w-full rounded-xl border bg-transparent p-2 font-normal" /></label>
      <label className="text-xs font-bold">New password<input type="password" minLength={8} value={form.password || ''} onChange={e => field('password', e.target.value)} placeholder="Leave blank to keep current password" className="mt-1 w-full rounded-xl border bg-transparent p-2 font-normal" /></label>
      <label className="text-xs font-bold">Role<select value={form.role} onChange={e => field('role', e.target.value as User['role'])} className="mt-1 w-full rounded-xl border bg-editorial-card p-2 font-normal"><option value="admin">Admin</option><option value="family">Family</option><option value="friend">Friend</option></select></label>
      <label className="text-xs font-bold">Profile picture<input type="file" accept="image/*" onChange={e => field('profilePictureUrl', e.target.files?.[0])} className="mt-1 block w-full text-xs font-normal" /></label>
      <div className="flex flex-wrap justify-end gap-2 md:col-span-2"><button type="submit" disabled={update.isPending} className="rounded-full bg-editorial-charcoal px-4 py-2 text-xs font-bold text-editorial-cream"><Save className="mr-1 inline h-4 w-4" />Save</button><button type="button" onClick={() => setConfirm(user.isActive ? 'deactivate' : 'reactivate')} className="rounded-full border px-4 py-2 text-xs font-bold">{user.isActive ? <ShieldOff className="mr-1 inline h-4 w-4" /> : <UserCheck className="mr-1 inline h-4 w-4" />}{user.isActive ? 'Deactivate' : 'Reactivate'}</button>{user.invitationPending && <button type="button" onClick={() => run(() => resend.mutateAsync({ id }))} className="rounded-full border px-4 py-2 text-xs font-bold"><Mail className="mr-1 inline h-4 w-4" />Resend invitation</button>}<button type="button" disabled={isSelf} title={isSelf ? 'You cannot delete your own administrator account.' : undefined} onClick={() => setConfirm('delete')} className="rounded-full border border-rose-500/30 px-4 py-2 text-xs font-bold text-rose-600 disabled:cursor-not-allowed disabled:opacity-35"><Trash2 className="mr-1 inline h-4 w-4" />Delete</button></div>
    </form>
    <section className="rounded-2xl border border-editorial-charcoal/10 p-5"><h3 className="font-serif text-xl">Account metadata</h3><dl className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['Role', user.role], ['Active state', user.isActive ? 'Active' : 'Inactive'], ['Two-factor authentication', user.twoFactorEnabled ? 'Enabled' : 'Disabled'], ['Invitation state', user.invitationPending ? 'Pending' : 'Complete'], ['Last login', date(user.lastLoginAt)], ['Created', date(user.createdAt)], ['Updated', date(user.updatedAt)], ['Password', user.hasPassword ? 'Configured' : 'Not configured']].map(([label, value]) => <div key={label} className="rounded-xl bg-editorial-charcoal/5 p-3"><dt className="text-[9px] font-bold uppercase text-editorial-charcoal/45">{label}</dt><dd className="mt-1 text-xs">{value}</dd></div>)}</dl></section>
    <section className="rounded-2xl border border-editorial-charcoal/10 p-5"><h3 className="font-serif text-xl">Badge progress</h3>{badges.isLoading ? <p className="mt-3 text-xs">Loading badge progress…</p> : badges.error ? <p role="alert" className="mt-3 text-xs text-rose-600">Badge progress could not be loaded.</p> : <><p className="mt-2 text-xs text-editorial-charcoal/55">{progress.earned} of {progress.total} active badges earned</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{badges.data?.map(badge => <div key={badge.id} className={`rounded-xl border p-3 text-xs ${badge.earned ? 'border-emerald-500/25 bg-emerald-500/5' : 'opacity-55'}`}><span className="font-bold">{badge.name}</span><span className="ml-2">{badge.earned ? 'Earned' : 'In progress'}</span></div>)}</div></>}</section>
    <section className="rounded-2xl border border-editorial-charcoal/10 p-5"><h3 className="font-serif text-xl">Giving history</h3>{payments.isLoading ? <p className="mt-3 text-xs">Loading payments…</p> : payments.error ? <p className="mt-3 text-xs text-rose-600">Payments could not be loaded.</p> : !payments.data?.payments.length ? <p className="mt-3 text-xs text-editorial-charcoal/50">No payment records.</p> : <div className="mt-3 overflow-x-auto"><table className="w-full min-w-[620px] text-left text-xs"><thead><tr className="border-b text-[9px] uppercase text-editorial-charcoal/45"><th className="py-2">Status</th><th>Type</th><th>Amount</th><th>Receipt</th></tr></thead><tbody>{payments.data.payments.map(payment => <tr key={payment.id} className="border-b border-editorial-charcoal/5"><td className="py-3 capitalize">{payment.status.replace('_', ' ')}</td><td className="capitalize">{payment.type}{payment.interval ? ` · ${payment.interval}` : ''}</td><td>${payment.amount.toLocaleString()} {payment.currency.toUpperCase()}</td><td>{payment.receipt.available && payment.receipt.url ? <a href={payment.receipt.url} target="_blank" rel="noreferrer" className="font-bold text-emerald-700 underline">Receipt</a> : '—'}</td></tr>)}</tbody></table></div>}</section>
    <section className="rounded-2xl border border-editorial-charcoal/10 p-5"><h3 className="font-serif text-xl">Prayer-wall activity</h3>{prayer.isLoading ? <p className="mt-3 text-xs">Loading activity…</p> : prayer.error ? <p className="mt-3 text-xs text-rose-600">Prayer activity could not be loaded.</p> : !prayer.data?.activity.length ? <p className="mt-3 text-xs text-editorial-charcoal/50">No prayer-wall activity.</p> : <div className="mt-3 space-y-2">{prayer.data.activity.map((activity, index) => <article key={`${activity.entityId}-${index}`} className="rounded-xl bg-editorial-charcoal/5 p-3 text-xs"><p className="font-bold capitalize">{activity.activityType}{activity.prayerType ? ` · ${activity.prayerType}` : ''}</p><p className="mt-1 text-editorial-charcoal/55">{activity.excerpt || activity.entityId}</p><p className="mt-1 text-[9px] text-editorial-charcoal/40">{date(activity.createdAt)}</p></article>)}</div>}</section>
    <ContractGap title="Commitments" />
    <ConfirmDialog open={!!confirm} title={confirm === 'delete' ? 'Delete this user?' : confirm === 'deactivate' ? 'Deactivate this user?' : 'Reactivate this user?'} description={confirm === 'delete' ? 'The account is immediately deactivated and permanent deletion may wait for subscription cancellation.' : confirm === 'deactivate' ? 'The user will lose access until an administrator reactivates the account.' : 'The user will regain access to their account.'} confirmLabel={confirm === 'delete' ? 'Delete user' : confirm === 'deactivate' ? 'Deactivate' : 'Reactivate'} destructive={confirm !== 'reactivate'} busy={update.isPending || remove.isPending} onCancel={() => setConfirm(null)} onConfirm={() => confirm && run(() => confirm === 'delete' ? remove.mutateAsync(id) : update.mutateAsync({ id, input: { isActive: confirm === 'reactivate' } }), confirm === 'delete' ? onBack : undefined)} />
  </div>;
}

function ContractGap({ title }: { title: string }) { return <section className="rounded-2xl border border-dashed border-amber-500/30 bg-amber-500/5 p-5"><h3 className="font-serif text-xl">{title}</h3><p className="mt-2 text-xs leading-relaxed text-editorial-charcoal/60">The endpoint exists, but its commitment items are declared as arbitrary objects in the updated OpenAPI document. Rendering is withheld until the response references the Commitment schema.</p></section>; }
