import React, { useState } from 'react';
import { ExternalLink, Eye, Heart, MessageCircle, RotateCcw, ShieldOff, Users, X } from 'lucide-react';
import type { components } from '../../api/generated';
import { ShareButton, threadLink } from '../PrayerWall';
import { type ModerationListParams, useManagedPrayerComment, useManagedPrayerComments, useManagedPrayerThread, useManagedPrayerThreads, useModerateDeleteComment, useModerateDeleteThread, useRestorePrayerComment, useRestorePrayerThread } from '../../api/hooks';
import { AdminListControls, AdminListState, AdminPagination, FilterField, useAdminListState } from './AdminList';
import { ConfirmDialog } from './ConfirmDialog';

type ManagedThread = components['schemas']['ManagedThread']; type ManagedComment = components['schemas']['ManagedComment'];
type Selection = { kind: 'thread'; item: ManagedThread } | { kind: 'comment'; item: ManagedComment };

export function AdminPrayerModeration() {
  const [selection, setSelection] = useState<Selection | null>(null); const [action, setAction] = useState<{ selection: Selection; action: 'remove' | 'restore' } | null>(null); const [reason, setReason] = useState(''); const [error, setError] = useState('');
  const removeThread = useModerateDeleteThread(); const restoreThread = useRestorePrayerThread(); const removeComment = useModerateDeleteComment(); const restoreComment = useRestorePrayerComment();
  const run = async () => { if (!action) return; setError(''); try { if (action.selection.kind === 'thread') { if (action.action === 'remove') await removeThread.mutateAsync({ id: action.selection.item.id, reason: reason.trim() }); else await restoreThread.mutateAsync(action.selection.item.id); } else if (action.action === 'remove') await removeComment.mutateAsync({ id: action.selection.item.id, reason: reason.trim() }); else await restoreComment.mutateAsync(action.selection.item.id); setAction(null); setReason(''); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Moderation action failed.'); } };
  const begin = (selection: Selection, nextAction: 'remove' | 'restore') => { setReason(''); setAction({ selection, action: nextAction }); };
  return <div className="space-y-5"><div><h2 className="text-2xl font-serif">Comments & threads moderation</h2><p className="text-xs text-editorial-charcoal/50">Review independent queues, inspect moderation metadata, and remove or restore content.</p></div>{error && <p role="alert" className="rounded-xl bg-rose-500/10 p-3 text-xs text-rose-600">{error}</p>}<div className="grid items-start gap-6 xl:grid-cols-2"><ThreadQueue onView={item => setSelection({ kind: 'thread', item })} onAction={(item, nextAction) => begin({ kind: 'thread', item }, nextAction)} /><CommentQueue onView={item => setSelection({ kind: 'comment', item })} onAction={(item, nextAction) => begin({ kind: 'comment', item }, nextAction)} /></div>
    <ModerationDetail selection={selection} onClose={() => setSelection(null)} />
    <ConfirmDialog open={!!action} title={action?.action === 'remove' ? `Remove ${action.selection.kind}?` : `Restore ${action?.selection.kind}?`} description={action?.action === 'remove' ? 'This hides the content from the public prayer wall and records the moderation reason.' : 'This makes the content visible again when its parent thread permits it.'} confirmLabel={action?.action === 'remove' ? 'Remove' : 'Restore'} destructive={action?.action === 'remove'} busy={removeThread.isPending || restoreThread.isPending || removeComment.isPending || restoreComment.isPending} reason={reason} onReasonChange={action?.action === 'remove' ? setReason : undefined} requireReason={action?.action === 'remove'} onCancel={() => { setAction(null); setReason(''); }} onConfirm={run} />
  </div>;
}

function ThreadQueue({ onView, onAction }: { onView: (item: ManagedThread) => void; onAction: (item: ManagedThread, action: 'remove' | 'restore') => void }) {
  const { query, update } = useAdminListState('prayer_threads', { page: 1, limit: 20, search: '', status: '', type: '' }); const list = useManagedPrayerThreads({ ...query, status: query.status || undefined, type: query.type || undefined } as ModerationListParams);
  return <section className="space-y-3"><h3 className="font-serif text-xl">Threads</h3><AdminListControls query={query} onChange={update} searchPlaceholder="Search post text or author"><FilterField label="Type"><select value={query.type} onChange={e => update({ type: e.target.value })}><option value="">Prayer and praise</option><option value="prayer">Prayer</option><option value="praise">Praise</option></select></FilterField><FilterField label="Status"><select value={query.status} onChange={e => update({ status: e.target.value })}><option value="">All</option><option value="visible">Visible</option><option value="removed">Removed</option></select></FilterField></AdminListControls><AdminListState loading={list.isLoading} error={list.error} empty={!list.data?.threads.length}><div className="space-y-3">{list.data?.threads.map(item => <ModerationCard key={item.id} item={item} onView={() => onView(item)} onAction={() => onAction(item, item.status === 'removed' ? 'restore' : 'remove')} />)}</div></AdminListState>{list.data && <AdminPagination page={list.data.page} limit={list.data.limit} total={list.data.total} totalPages={list.data.totalPages} onChange={update} />}</section>;
}

function CommentQueue({ onView, onAction }: { onView: (item: ManagedComment) => void; onAction: (item: ManagedComment, action: 'remove' | 'restore') => void }) {
  const { query, update } = useAdminListState('prayer_comments', { page: 1, limit: 20, search: '', status: '', type: '' }); const list = useManagedPrayerComments({ ...query, status: query.status || undefined, type: query.type || undefined } as ModerationListParams);
  return <section className="space-y-3"><h3 className="font-serif text-xl">Comments</h3><AdminListControls query={query} onChange={update} searchPlaceholder="Search comment text or author"><FilterField label="Parent type"><select value={query.type} onChange={e => update({ type: e.target.value })}><option value="">Prayer and praise</option><option value="prayer">Prayer</option><option value="praise">Praise</option></select></FilterField><FilterField label="Status"><select value={query.status} onChange={e => update({ status: e.target.value })}><option value="">All</option><option value="visible">Visible</option><option value="removed">Removed</option></select></FilterField></AdminListControls><AdminListState loading={list.isLoading} error={list.error} empty={!list.data?.comments.length}><div className="space-y-3">{list.data?.comments.map(item => <ModerationCard key={item.id} item={item} onView={() => onView(item)} onAction={() => onAction(item, item.status === 'removed' ? 'restore' : 'remove')} />)}</div></AdminListState>{list.data && <AdminPagination page={list.data.page} limit={list.data.limit} total={list.data.total} totalPages={list.data.totalPages} onChange={update} />}</section>;
}

function ModerationCard({ item, onView, onAction }: { item: ManagedThread | ManagedComment; onView: () => void; onAction: () => void }) {
  const isThread = 'type' in item; const threadId = isThread ? item.id : item.threadId; const author = item.authorDisplayName || (item.isAnonymous ? 'Anonymous' : item.author ? `${item.author.firstName}${item.author.lastName ? ` ${item.author.lastName}` : ''}` : 'Unknown author');
  return <article className={`overflow-hidden rounded-3xl border bg-editorial-card ${!isThread ? 'ml-5 shadow-[inset_3px_0_0_theme(colors.sky.400)]' : ''}`}><div className="p-5"><div className="flex items-start gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-editorial-charcoal/5 text-sm font-bold">{author.charAt(0).toUpperCase()}</div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold">{author}</p><p className="text-[9px] uppercase tracking-wider text-editorial-charcoal/45">{isThread ? item.type : 'comment'} · {new Date(item.createdAt).toLocaleDateString()}</p></div><span className={`rounded-full px-2 py-1 text-[9px] font-bold uppercase ${item.status === 'visible' ? 'bg-emerald-500/10 text-emerald-700' : 'bg-rose-500/10 text-rose-700'}`}>{item.status}</span></div><p className="mt-3 whitespace-pre-wrap text-sm leading-relaxed text-editorial-charcoal/80">{item.body}</p><div className="mt-4 flex flex-wrap items-center gap-2 text-[10px]"><span className="flex items-center gap-1 rounded-full border px-3 py-1.5"><Heart className="h-3.5 w-3.5" />{isThread ? item.reactions.likeCount : '—'}</span>{isThread && <><span className="flex items-center gap-1 rounded-full border px-3 py-1.5"><Users className="h-3.5 w-3.5" />{item.reactions.joinPrayerCount}</span><span className="flex items-center gap-1 rounded-full border px-3 py-1.5"><MessageCircle className="h-3.5 w-3.5" />{item.commentCount}</span></>}<span className="text-editorial-charcoal/45">Created {new Date(item.createdAt).toLocaleString()}</span></div><p className="mt-2 text-[10px] text-editorial-charcoal/45">Removal source: {item.removalSource || 'None'}{item.removalReason ? ` · Reason: ${item.removalReason}` : ''}</p><div className="mt-4 flex flex-wrap justify-end gap-2"><ShareButton url={threadLink(threadId, isThread ? undefined : item.id)} /><a href={`/prayer-wall/${encodeURIComponent(threadId)}`} className="rounded-full border px-3 py-1.5 text-xs font-bold"><ExternalLink className="mr-1 inline h-3 w-3" />View entire thread</a><button onClick={onView} className="rounded-full border px-3 py-1.5 text-xs"><Eye className="mr-1 inline h-3 w-3" />Metadata</button><button onClick={onAction} className={`rounded-full border px-3 py-1.5 text-xs ${item.status === 'visible' ? 'text-rose-600' : 'text-emerald-700'}`}>{item.status === 'visible' ? <ShieldOff className="mr-1 inline h-3 w-3" /> : <RotateCcw className="mr-1 inline h-3 w-3" />}{item.status === 'visible' ? 'Remove' : 'Restore'}</button></div></div></div></div></article>;
}

function ModerationDetail({ selection, onClose }: { selection: Selection | null; onClose: () => void }) {
  const thread = useManagedPrayerThread(selection?.kind === 'thread' ? selection.item.id : '', selection?.kind === 'thread'); const comment = useManagedPrayerComment(selection?.kind === 'comment' ? selection.item.id : '', selection?.kind === 'comment');
  if (!selection) return null; const item = selection.kind === 'thread' ? thread.data?.thread || selection.item : comment.data?.comment || selection.item; const loading = selection.kind === 'thread' ? thread.isLoading : comment.isLoading; const error = selection.kind === 'thread' ? thread.error : comment.error;
  return <div className="fixed inset-0 z-[90] flex items-center justify-center bg-black/55 p-4" role="presentation" onMouseDown={event => { if (event.target === event.currentTarget) onClose(); }}><div role="dialog" aria-modal="true" className="max-h-[85vh] w-full max-w-2xl overflow-auto rounded-3xl bg-editorial-card p-6"><div className="flex items-start justify-between"><div><p className="text-[9px] font-bold uppercase tracking-widest text-editorial-charcoal/45">Moderation detail</p><h3 className="font-serif text-2xl capitalize">{selection.kind}</h3></div><button onClick={onClose} aria-label="Close"><X className="h-5 w-5" /></button></div>{loading ? <p className="mt-5 text-sm">Loading details…</p> : error ? <p role="alert" className="mt-5 text-sm text-rose-600">The detail endpoint could not be loaded; showing queue data.</p> : null}<p className="mt-5 whitespace-pre-wrap rounded-2xl bg-editorial-charcoal/5 p-4 text-sm">{item.body}</p><dl className="mt-4 grid gap-3 sm:grid-cols-2">{[['Status', item.status], ['Removal source', item.removalSource || 'None'], ['Removal reason', item.removalReason || 'None'], ['Removed at', item.removedAt ? new Date(item.removedAt).toLocaleString() : 'Never'], ['Created', new Date(item.createdAt).toLocaleString()], ['Updated', new Date(item.updatedAt).toLocaleString()]].map(([label, value]) => <div key={label} className="rounded-xl border p-3"><dt className="text-[9px] font-bold uppercase text-editorial-charcoal/45">{label}</dt><dd className="mt-1 text-xs">{value}</dd></div>)}</dl>{selection.kind === 'thread' && thread.data && <p className="mt-4 text-xs text-editorial-charcoal/55">{thread.data.comments.total} comments are attached to this thread.</p>}</div></div>;
}
